eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.classified.cfapps.io/eureka/           
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}

logging:
  level:
    org.springframework.cloud: DEBUG
logging:
  level:
    com.confidential.platform: DEBUG
    org.springframework.web: DEBUG

