eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.classified.credentials.uri:http://127.0.0.1:8761}/eureka/
logging:
  level:
    com.confidential.platform: DEBUG
    org.springframework.web: DEBUG

